[package]
name = "licensa"
version = "0.1.0"
edition = "2021"
description = "CLI tool to enforce, verify, apply and modify file license headers"
authors = ["Nelson Dominguez <ekkolon@proton.me>"]
categories = ["command-line-utilities", "development-tools"]
keywords = ["licensing", "cli"]
license = "Apache-2.0"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [build-dependencies]
# lazy_static = "1"

[dependencies]
chrono = { version = "0.4.31" }
clap = { version = "4.4.18", features = ["derive"] }
directories = "5.0.1"
env_logger = "0.11.0"
glob = "0.3.1"
log = "0.4.20"
reqwest = "0.11.23"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = { version = "2.5.0", features = ["serde"] }
mimalloc = { version = "*", default-features = false }
lazy_static = "1"
thiserror = "1.0.56"
anyhow = "1.0.79"
derive_more = { version = "0.99.17", features = ["display"] }
regex = "1.10.3"
tabled = "0.15.0"
ignore = "0.4.22"
crossbeam-channel = "0.5.11"
rayon = "1.8.1"
colored = "2.1.0"

[badges]
maintenance = { status = "experimental" }

[profile.dev]
# Disabling debug info speeds up builds a bunch and we don't rely on it for debugging that much.
debug = 0

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3.9.0"
