[package]
name = "licensia"
version = "0.1.0"
edition = "2021"
description = "CLI tool to enforce, verify, apply and modify file license headers"
authors = ["Nelson Dominguez <ekkolon@proton.me>"]
categories = ["command-line-utilities", "development-tools"]
keywords = ["licensing", "cli"]
license = "Apache-2.0"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31" }
clap = { version = "4.4.18", features = ["derive"] }
directories = "5.0.1"
env_logger = "0.11.0"
glob = "0.3.1"
log = "0.4.20"
reqwest = "0.11.23"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_yaml = "0.9.30"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = "2.5.0"

[badges]
maintenance = { status = "experimental" }
