# https://docs.codecov.com/docs/codecovyml-reference#coverage
coverage:
  precision: 1 # e.g. 89.1%
  round: down

  # https://docs.codecov.com/docs/coverage-configuration#section-range
  range: 85..100

  # https://docs.codecov.com/docs/commit-status
  status:
    project:
      default:
        threshold: 1% # Avoid false negatives
ignore:
  - "examples"
  - "benches"

# https://docs.codecov.com/docs/pull-request-comments
comment:
  # make the comments less noisy
  require_changes: true
