use serde::Serialize;

pub trait Step
where
    Self: Serialize,
{
    fn run(&mut self) -> crate::Result<()>;
}
pub trait Exit {
    /// Exits the program with an error message.
    fn exit(self) -> !;
}

pub trait UnwrapOrExit {
    type Output;

    /// Unwraps the value if successful, or exits the program with the provided error.
    fn unwrap_or_exit(self) -> Self::Output;
}

impl<T, E: Exit> UnwrapOrExit for Result<T, E> {
    type Output = T;

    fn unwrap_or_exit(self) -> Self::Output {
        match self {
            Ok(value) => value,
            Err(err) => err.exit(),
        }
    }
}

pub trait UnwrapOrExitWith {
    type Output;
    type Err: Exit;

    /// Unwraps the value if successful, or exits the program with the provided error.
    fn unwrap_or_exit_with(self, err: Self::Err) -> Self::Output;

    /// Unwraps the value if successful, or exits the program with an error generated by the closure.
    fn unwrap_or_else_exit_with<F>(self, err_fn: F) -> Self::Output
    where
        F: FnOnce() -> Self::Err;
}

impl<T, E: Exit> UnwrapOrExitWith for Result<T, E> {
    type Output = T;
    type Err = crate::Error;

    fn unwrap_or_exit_with(self, err: crate::Error) -> Self::Output {
        match self {
            Ok(value) => value,
            Err(_) => err.exit(),
        }
    }

    fn unwrap_or_else_exit_with<F>(self, err_fn: F) -> T
    where
        F: FnOnce() -> crate::Error,
    {
        match self {
            Ok(value) => value,
            Err(_) => err_fn().exit(),
        }
    }
}

impl<T> UnwrapOrExitWith for Option<T> {
    type Output = T;
    type Err = crate::Error;

    fn unwrap_or_exit_with(self, err: crate::Error) -> T {
        match self {
            Some(value) => value,
            None => err.exit(),
        }
    }

    fn unwrap_or_else_exit_with<F>(self, err_fn: F) -> Self::Output
    where
        F: FnOnce() -> crate::Error,
    {
        match self {
            Some(value) => value,
            None => err_fn().exit(),
        }
    }
}
